#!/usr/bin/env python3.6
#
# This file is part of superwaspd.
#
# superwaspd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# superwaspd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with superwaspd.  If not, see <http://www.gnu.org/licenses/>.

"""Front end for the SuperWASP weather log the Warwick one-metre telescope"""

import datetime
import urllib.request
import Pyro4
import astropy.time
from warwick.observatory.common import daemons, log

# Set automatically when generating RPM package
SOFTWARE_VERSION = 'UNKNOWN'

WEATHER_URI = 'http://192.168.0.53/public/weather.log'
QUERY_TIMEOUT = 3

# pylint: disable=broad-except
# pylint: disable=too-few-public-methods
# pylint: disable=no-self-use

class SuperWASPWeatherDaemon:
    """Wraps a web request to the SuperWASP Weather log"""
    def __init__(self):
        self._query_error = False

    @Pyro4.expose
    def last_measurement(self):
        """Query the latest valid measurement.
        May return None if no data is available"""
        try:
            with urllib.request.urlopen(WEATHER_URI, timeout=QUERY_TIMEOUT) as response:
                data = response.readlines()[-1].decode('ascii').split()

            # Convert swasp jd to UTC datetime
            date = astropy.time.Time(float(data[0]), format='jd').datetime

            if self._query_error:
                log.info('superwaspd', 'Restored contact with SuperWASP weather log')
                self._query_error = False

            return {
                'date': date.strftime('%Y-%m-%dT%H:%M:%SZ'),
                'jd' : round(float(data[0]), 6),
                'sky_temp': round(float(data[8]), 2),
                'wind_speed' : int(data[1]),
                'wind_direction' : int(data[2]),
                'ext_temperature' : round(float(data[11]), 2),
                'ext_humidity': round(float(data[14]), 1),
                'dew_point_delta': round(float(data[11]) - float(data[17]), 2),
                'pressure': round(float(data[5]), 2),
                'software_version': SOFTWARE_VERSION
            }

        except Exception as exception:
            print('{} ERROR: failed to query from SuperWASP weather log: {}' \
                  .format(datetime.datetime.utcnow(), str(exception)))

            if not self._query_error:
                log.error('superwaspd', 'Lost contact with SuperWASP weather log')
                self._query_error = True

            return None

if __name__ == '__main__':
    daemons.superwasp_log.launch(SuperWASPWeatherDaemon())
